package com.finance.tracker.mapper;

import com.finance.tracker.dto.WalletDTO;
import com.finance.tracker.model.Wallet;
import org.springframework.stereotype.Component;

@Component
public class WalletMapper {

    public WalletDTO toDTO(Wallet entity) {
        if (entity == null) return null;
        return WalletDTO.builder()
                .id(entity.getId())
                .name(entity.getName())
                .balance(entity.getBalance())
                .currency(entity.getCurrency())
                .note(entity.getNote())
                .createdAt(entity.getCreatedAt())
                .build();
    }

    public Wallet toEntity(WalletDTO dto) {
        if (dto == null) return null;
        return Wallet.builder()
                .id(dto.getId())
                .name(dto.getName())
                .balance(dto.getBalance())
                .currency(dto.getCurrency())
                .note(dto.getNote())
                .build(); // createdAt is usually generated by DB or @Builder.Default
    }
}
